### ISSUE TITLE
Come back on documentation and update it !

### ISSUE THREAD

**Issue by zepouet** [Treeptik/CloudUnit-CLI#10]

**Comment by Kan23** [comment]
I found errors, but I don't sure they are errors : 
- echo (always return 0, I don't understand "CU command" so I don't sure)
- ~~list-snapshot (org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "displayTag" (Class fr.treeptik.cloudunit.cli.model.Snapshot))~~
- ~~display-modules and informations (No modules found)~~
- ~~rm-snapshot (bad description)~~
- ~~No error message if an application doesn't have module when we try to remove one, or if an application have this module when we try to remove one.~~
